#!/usr/bin/env bash
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

pyenv exec python3 ~/scripts/showmap.py
read -p $'Press any key to continue...\n' -n1 -s
